### ISSUE TITLE
斷線問題

### ISSUE THREAD

**Issue by kevinlin0638** [kevinconan/Aries#3]
很棒的登入器，發現了ㄧ些小問題
發現除了本地端連線不會斷線外，外連的大概五分鐘左右就會斷線到登入畫面。

**Comment by Diluka** [comment]
减小了每次转写的缓冲大小之后，有效的解决了断线问题，还没有发布成品，源码自己构建试试吧。目前应该调多大还在尝试中。

https://github.com/kevinconan/Aries/blob/72eef094cdc279b40f8e12f7f7e1ce66d6b84d02/Aries/Aries.Lib/PortForwardingWorker.cs#L117
